### ISSUE TITLE
Ability to download recommendation file

### ISSUE THREAD

**Issue by Nautman** [digitalungdom-se/infrarays.se#33]

**Comment by Zigolox** [comment]
Make the teacher able to do it?

**Comment by Nautman** [comment]
I think it's actually not possible for a teacher to upload or remove a recommendation letter. Could @kelszo confirm this so we can close this issue?

**Comment by kelszo** [comment]
Yes, it is not possible due to security reasons. Can be solved if needed though. Reopen this issue if further discussion is needed.
