### ISSUE TITLE
Clarifying recommendation letter text

### ISSUE THREAD

**Issue by Zigolox** [digitalungdom-se/infrarays.se#45]
Change it to 

Thank you for taking interest in writing a letter of recommendation! 

The letter must be written, signed, and sent by the student's teacher, coach, or such. Maximum 1 page per letter. 

The student will not be able to see the letter but will receive a notification once it is uploaded. The file must be a PDF and the size limit is 5 MB.

**Comment by Nautman** [comment]
Do you meant that you want them divided into paragraphs?

**Comment by Zigolox** [comment]
Yes but also change some wording

**Comment by Nautman** [comment]
What wording?

**Comment by Zigolox** [comment]
Yup and some commas
