### ISSUE TITLE
How should survey statistics be presented?

### ISSUE THREAD

**Issue by Nautman** [digitalungdom-se/infrarays.se#61]
I would love some help from you @Zigolox @kelszo @sakerhetspolisen @charlesmaddock if you have any ideas how the survey data should be presented. Currently, we collect a number of data points from applicants. These are:

* City: The city from where they live
* School: Which school they attend
* Gender: Male / female / other / do not want to specify
* Grade for application portal: between 1 - 5 
* Grade for application process between 1 - 5 (this is different as the previous measures what people think of the actual website)
* Improvement: Text field where they can explain what they would like to see improved
* Informant: Who informed them of Rays. This is free text where they can write anything.

**Comment by Zigolox** [comment]
It would be cool to use open street map to show [location](https://nominatim.org/release-docs/develop/api/Search/)

**Comment by Zigolox** [comment]
The grades are most interesting when combined so perhaps show average and standard deviation

**Comment by Zigolox** [comment]
Box plot would also work

**Comment by Nautman** [comment]
I think a map with locations is a cool idea, but perhaps the location is difficult since we don't have exact locations.
